In [1]:
import yfinance as yf
import pandas as pd

In [2]:
%cd ..

/Users/carlos.redondo/Projects/strategy

In [3]:
from src.data.downloader import DataDownloader
from src.data.csv_data_handler import CSVDataHandler
from src.execution.simulated_execution import SimulatedExecutionHandler

In [4]:
execution = SimulatedExecutionHandler()

execution.event_queue = []

class DummyOrder:
    timestamp = "2020-01-01"
    symbol = "SPY"
    quantity = 100
    side = "BUY"

execution.execute_order(DummyOrder(), 100)

print(execution.event_queue[0].fill_price)
print(execution.event_queue[0].commission)

100.05
5.0025

In [5]:
downloader = DataDownloader()
df = downloader.get("SPY", "2015-01-01", "2022-01-01", refresh=True)

handler = CSVDataHandler(df, "SPY")

while True:
    bar = handler.get_next_bar()
    if bar is None:
        break
    print(bar)

[*********************100%***********************]  1 of 1 completed

MarketEvent(timestamp=Timestamp('2015-01-02 00:00:00'), symbol='SPY', price=Ticker
SPY    170.589645
Name: 2015-01-02 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-01-05 00:00:00'), symbol='SPY', price=Ticker
SPY    167.508804
Name: 2015-01-05 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-01-06 00:00:00'), symbol='SPY', price=Ticker
SPY    165.931046
Name: 2015-01-06 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-01-07 00:00:00'), symbol='SPY', price=Ticker
SPY    167.998749
Name: 2015-01-07 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-01-08 00:00:00'), symbol='SPY', price=Ticker
SPY    170.97995
Name: 2015-01-08 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-01-09 00:00:00'), symbol='SPY', price=Ticker
SPY    169.609695
Name: 2015-01-09 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-01-12 00:00:00'), symbol='SPY', price=Ticker
SPY    168.281097
Name: 2015-01-12 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-01-13 00:00:00'), symbol='SPY', price=Ticker
SPY    167.807755
Name: 2015-01-13 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-01-14 00:00:00'), symbol='SPY', price=Ticker
SPY    166.794693
Name: 2015-01-14 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-01-15 00:00:00'), symbol='SPY', price=Ticker
SPY    165.266785
Name: 2015-01-15 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-01-16 00:00:00'), symbol='SPY', price=Ticker
SPY    167.434052
Name: 2015-01-16 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-01-20 00:00:00'), symbol='SPY', price=Ticker
SPY    167.791183
Name: 2015-01-20 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-01-21 00:00:00'), symbol='SPY', price=Ticker
SPY    168.638184
Name: 2015-01-21 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-01-22 00:00:00'), symbol='SPY', price=Ticker
SPY    171.14595
Name: 2015-01-22 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-01-23 00:00:00'), symbol='SPY', price=Ticker
SPY    170.207611
Name: 2015-01-23 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-01-26 00:00:00'), symbol='SPY', price=Ticker
SPY    170.606247
Name: 2015-01-26 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-01-27 00:00:00'), symbol='SPY', price=Ticker
SPY    168.35585
Name: 2015-01-27 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-01-28 00:00:00'), symbol='SPY', price=Ticker
SPY    166.196793
Name: 2015-01-28 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-01-29 00:00:00'), symbol='SPY', price=Ticker
SPY    167.733047
Name: 2015-01-29 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-01-30 00:00:00'), symbol='SPY', price=Ticker
SPY    165.623749
Name: 2015-01-30 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-02-02 00:00:00'), symbol='SPY', price=Ticker
SPY    167.674866
Name: 2015-02-02 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-02-03 00:00:00'), symbol='SPY', price=Ticker
SPY    170.099701
Name: 2015-02-03 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-02-04 00:00:00'), symbol='SPY', price=Ticker
SPY    169.45195
Name: 2015-02-04 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-02-05 00:00:00'), symbol='SPY', price=Ticker
SPY    171.162613
Name: 2015-02-05 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-02-06 00:00:00'), symbol='SPY', price=Ticker
SPY    170.689285
Name: 2015-02-06 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-02-09 00:00:00'), symbol='SPY', price=Ticker
SPY    169.925262
Name: 2015-02-09 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-02-10 00:00:00'), symbol='SPY', price=Ticker
SPY    171.73555
Name: 2015-02-10 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-02-11 00:00:00'), symbol='SPY', price=Ticker
SPY    171.835236
Name: 2015-02-11 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-02-12 00:00:00'), symbol='SPY', price=Ticker
SPY    173.487732
Name: 2015-02-12 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-02-13 00:00:00'), symbol='SPY', price=Ticker
SPY    174.201874
Name: 2015-02-13 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-02-17 00:00:00'), symbol='SPY', price=Ticker
SPY    174.475906
Name: 2015-02-17 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-02-18 00:00:00'), symbol='SPY', price=Ticker
SPY    174.492493
Name: 2015-02-18 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-02-19 00:00:00'), symbol='SPY', price=Ticker
SPY    174.36792
Name: 2015-02-19 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-02-20 00:00:00'), symbol='SPY', price=Ticker
SPY    175.414261
Name: 2015-02-20 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-02-23 00:00:00'), symbol='SPY', price=Ticker
SPY    175.389359
Name: 2015-02-23 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-02-24 00:00:00'), symbol='SPY', price=Ticker
SPY    175.887573
Name: 2015-02-24 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-02-25 00:00:00'), symbol='SPY', price=Ticker
SPY    175.738129
Name: 2015-02-25 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-02-26 00:00:00'), symbol='SPY', price=Ticker
SPY    175.530548
Name: 2015-02-26 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-02-27 00:00:00'), symbol='SPY', price=Ticker
SPY    174.932617
Name: 2015-02-27 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-03-02 00:00:00'), symbol='SPY', price=Ticker
SPY    176.037018
Name: 2015-03-02 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-03-03 00:00:00'), symbol='SPY', price=Ticker
SPY    175.314636
Name: 2015-03-03 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-03-04 00:00:00'), symbol='SPY', price=Ticker
SPY    174.5755
Name: 2015-03-04 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-03-05 00:00:00'), symbol='SPY', price=Ticker
SPY    174.766571
Name: 2015-03-05 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-03-06 00:00:00'), symbol='SPY', price=Ticker
SPY    172.308533
Name: 2015-03-06 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-03-09 00:00:00'), symbol='SPY', price=Ticker
SPY    173.02269
Name: 2015-03-09 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-03-10 00:00:00'), symbol='SPY', price=Ticker
SPY    170.215927
Name: 2015-03-10 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-03-11 00:00:00'), symbol='SPY', price=Ticker
SPY    169.817337
Name: 2015-03-11 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-03-12 00:00:00'), symbol='SPY', price=Ticker
SPY    171.976425
Name: 2015-03-12 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-03-13 00:00:00'), symbol='SPY', price=Ticker
SPY    170.921768
Name: 2015-03-13 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-03-16 00:00:00'), symbol='SPY', price=Ticker
SPY    173.205414
Name: 2015-03-16 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-03-17 00:00:00'), symbol='SPY', price=Ticker
SPY    172.690567
Name: 2015-03-17 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-03-18 00:00:00'), symbol='SPY', price=Ticker
SPY    174.766571
Name: 2015-03-18 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-03-19 00:00:00'), symbol='SPY', price=Ticker
SPY    173.96936
Name: 2015-03-19 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-03-20 00:00:00'), symbol='SPY', price=Ticker
SPY    175.504929
Name: 2015-03-20 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-03-23 00:00:00'), symbol='SPY', price=Ticker
SPY    175.162964
Name: 2015-03-23 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-03-24 00:00:00'), symbol='SPY', price=Ticker
SPY    174.178696
Name: 2015-03-24 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-03-25 00:00:00'), symbol='SPY', price=Ticker
SPY    171.626343
Name: 2015-03-25 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-03-26 00:00:00'), symbol='SPY', price=Ticker
SPY    171.217651
Name: 2015-03-26 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-03-27 00:00:00'), symbol='SPY', price=Ticker
SPY    171.609665
Name: 2015-03-27 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-03-30 00:00:00'), symbol='SPY', price=Ticker
SPY    173.703262
Name: 2015-03-30 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-03-31 00:00:00'), symbol='SPY', price=Ticker
SPY    172.185135
Name: 2015-03-31 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-04-01 00:00:00'), symbol='SPY', price=Ticker
SPY    171.576279
Name: 2015-04-01 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-04-02 00:00:00'), symbol='SPY', price=Ticker
SPY    172.193558
Name: 2015-04-02 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-04-06 00:00:00'), symbol='SPY', price=Ticker
SPY    173.352921
Name: 2015-04-06 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-04-07 00:00:00'), symbol='SPY', price=Ticker
SPY    172.89418
Name: 2015-04-07 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-04-08 00:00:00'), symbol='SPY', price=Ticker
SPY    173.478073
Name: 2015-04-08 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-04-09 00:00:00'), symbol='SPY', price=Ticker
SPY    174.245453
Name: 2015-04-09 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-04-10 00:00:00'), symbol='SPY', price=Ticker
SPY    175.19632
Name: 2015-04-10 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-04-13 00:00:00'), symbol='SPY', price=Ticker
SPY    174.403946
Name: 2015-04-13 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-04-14 00:00:00'), symbol='SPY', price=Ticker
SPY    174.737656
Name: 2015-04-14 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-04-15 00:00:00'), symbol='SPY', price=Ticker
SPY    175.521606
Name: 2015-04-15 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-04-16 00:00:00'), symbol='SPY', price=Ticker
SPY    175.471588
Name: 2015-04-16 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-04-17 00:00:00'), symbol='SPY', price=Ticker
SPY    173.453079
Name: 2015-04-17 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-04-20 00:00:00'), symbol='SPY', price=Ticker
SPY    175.037842
Name: 2015-04-20 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-04-21 00:00:00'), symbol='SPY', price=Ticker
SPY    174.829361
Name: 2015-04-21 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-04-22 00:00:00'), symbol='SPY', price=Ticker
SPY    175.688461
Name: 2015-04-22 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-04-23 00:00:00'), symbol='SPY', price=Ticker
SPY    176.130554
Name: 2015-04-23 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-04-24 00:00:00'), symbol='SPY', price=Ticker
SPY    176.539261
Name: 2015-04-24 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-04-27 00:00:00'), symbol='SPY', price=Ticker
SPY    175.805176
Name: 2015-04-27 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-04-28 00:00:00'), symbol='SPY', price=Ticker
SPY    176.364075
Name: 2015-04-28 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-04-29 00:00:00'), symbol='SPY', price=Ticker
SPY    175.638382
Name: 2015-04-29 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-04-30 00:00:00'), symbol='SPY', price=Ticker
SPY    173.878464
Name: 2015-04-30 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-05-01 00:00:00'), symbol='SPY', price=Ticker
SPY    175.763535
Name: 2015-05-01 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-05-04 00:00:00'), symbol='SPY', price=Ticker
SPY    176.263992
Name: 2015-05-04 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-05-05 00:00:00'), symbol='SPY', price=Ticker
SPY    174.245453
Name: 2015-05-05 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-05-06 00:00:00'), symbol='SPY', price=Ticker
SPY    173.528076
Name: 2015-05-06 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-05-07 00:00:00'), symbol='SPY', price=Ticker
SPY    174.220459
Name: 2015-05-07 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-05-08 00:00:00'), symbol='SPY', price=Ticker
SPY    176.514191
Name: 2015-05-08 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-05-11 00:00:00'), symbol='SPY', price=Ticker
SPY    175.671753
Name: 2015-05-11 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-05-12 00:00:00'), symbol='SPY', price=Ticker
SPY    175.146271
Name: 2015-05-12 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-05-13 00:00:00'), symbol='SPY', price=Ticker
SPY    175.179672
Name: 2015-05-13 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-05-14 00:00:00'), symbol='SPY', price=Ticker
SPY    177.006332
Name: 2015-05-14 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-05-15 00:00:00'), symbol='SPY', price=Ticker
SPY    177.198151
Name: 2015-05-15 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-05-18 00:00:00'), symbol='SPY', price=Ticker
SPY    177.748734
Name: 2015-05-18 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-05-19 00:00:00'), symbol='SPY', price=Ticker
SPY    177.690308
Name: 2015-05-19 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-05-20 00:00:00'), symbol='SPY', price=Ticker
SPY    177.565155
Name: 2015-05-20 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-05-21 00:00:00'), symbol='SPY', price=Ticker
SPY    178.082291
Name: 2015-05-21 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-05-22 00:00:00'), symbol='SPY', price=Ticker
SPY    177.656967
Name: 2015-05-22 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-05-26 00:00:00'), symbol='SPY', price=Ticker
SPY    175.746841
Name: 2015-05-26 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-05-27 00:00:00'), symbol='SPY', price=Ticker
SPY    177.41507
Name: 2015-05-27 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-05-28 00:00:00'), symbol='SPY', price=Ticker
SPY    177.21492
Name: 2015-05-28 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-05-29 00:00:00'), symbol='SPY', price=Ticker
SPY    176.1138
Name: 2015-05-29 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-06-01 00:00:00'), symbol='SPY', price=Ticker
SPY    176.472565
Name: 2015-06-01 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-06-02 00:00:00'), symbol='SPY', price=Ticker
SPY    176.297363
Name: 2015-06-02 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-06-03 00:00:00'), symbol='SPY', price=Ticker
SPY    176.764404
Name: 2015-06-03 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-06-04 00:00:00'), symbol='SPY', price=Ticker
SPY    175.271439
Name: 2015-06-04 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-06-05 00:00:00'), symbol='SPY', price=Ticker
SPY    174.971161
Name: 2015-06-05 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-06-08 00:00:00'), symbol='SPY', price=Ticker
SPY    173.895126
Name: 2015-06-08 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-06-09 00:00:00'), symbol='SPY', price=Ticker
SPY    173.870117
Name: 2015-06-09 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-06-10 00:00:00'), symbol='SPY', price=Ticker
SPY    175.955399
Name: 2015-06-10 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-06-11 00:00:00'), symbol='SPY', price=Ticker
SPY    176.522537
Name: 2015-06-11 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-06-12 00:00:00'), symbol='SPY', price=Ticker
SPY    175.171295
Name: 2015-06-12 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-06-15 00:00:00'), symbol='SPY', price=Ticker
SPY    174.420639
Name: 2015-06-15 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-06-16 00:00:00'), symbol='SPY', price=Ticker
SPY    175.371506
Name: 2015-06-16 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-06-17 00:00:00'), symbol='SPY', price=Ticker
SPY    175.655075
Name: 2015-06-17 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-06-18 00:00:00'), symbol='SPY', price=Ticker
SPY    177.481827
Name: 2015-06-18 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-06-19 00:00:00'), symbol='SPY', price=Ticker
SPY    176.693924
Name: 2015-06-19 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-06-22 00:00:00'), symbol='SPY', price=Ticker
SPY    177.599091
Name: 2015-06-22 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-06-23 00:00:00'), symbol='SPY', price=Ticker
SPY    177.724869
Name: 2015-06-23 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-06-24 00:00:00'), symbol='SPY', price=Ticker
SPY    176.434067
Name: 2015-06-24 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-06-25 00:00:00'), symbol='SPY', price=Ticker
SPY    175.897675
Name: 2015-06-25 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-06-26 00:00:00'), symbol='SPY', price=Ticker
SPY    175.864151
Name: 2015-06-26 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-06-29 00:00:00'), symbol='SPY', price=Ticker
SPY    172.176193
Name: 2015-06-29 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-06-30 00:00:00'), symbol='SPY', price=Ticker
SPY    172.536591
Name: 2015-06-30 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-07-01 00:00:00'), symbol='SPY', price=Ticker
SPY    173.919586
Name: 2015-07-01 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-07-02 00:00:00'), symbol='SPY', price=Ticker
SPY    173.76033
Name: 2015-07-02 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-07-06 00:00:00'), symbol='SPY', price=Ticker
SPY    173.265823
Name: 2015-07-06 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-07-07 00:00:00'), symbol='SPY', price=Ticker
SPY    174.355423
Name: 2015-07-07 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-07-08 00:00:00'), symbol='SPY', price=Ticker
SPY    171.430283
Name: 2015-07-08 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-07-09 00:00:00'), symbol='SPY', price=Ticker
SPY    171.740341
Name: 2015-07-09 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-07-10 00:00:00'), symbol='SPY', price=Ticker
SPY    173.902878
Name: 2015-07-10 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-07-13 00:00:00'), symbol='SPY', price=Ticker
SPY    175.82225
Name: 2015-07-13 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-07-14 00:00:00'), symbol='SPY', price=Ticker
SPY    176.58493
Name: 2015-07-14 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-07-15 00:00:00'), symbol='SPY', price=Ticker
SPY    176.526291
Name: 2015-07-15 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-07-16 00:00:00'), symbol='SPY', price=Ticker
SPY    177.942795
Name: 2015-07-16 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-07-17 00:00:00'), symbol='SPY', price=Ticker
SPY    178.093643
Name: 2015-07-17 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-07-20 00:00:00'), symbol='SPY', price=Ticker
SPY    178.185852
Name: 2015-07-20 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-07-21 00:00:00'), symbol='SPY', price=Ticker
SPY    177.481827
Name: 2015-07-21 00:00:00, dtype: float64)
MarketEvent(timestamp=Timestamp('2015-07-22 00:00:00'), symbol='SPY', price=Ticker
SPY    177.163315
Name: 2015-07-22 00:00:00, dtype: float64)

In [6]:
df.describe()

Price         Close         High          Low         Open        Volume
Ticker          SPY          SPY          SPY          SPY           SPY
count   1763.000000  1763.000000  1763.000000  1763.000000  1.763000e+03
mean     252.896739   254.140091   251.448915   252.859330  9.146561e+07
std       75.207558    75.533797    74.804043    75.187693  4.948592e+07
min      154.980865   156.031818   152.881622   154.540142  2.027000e+07
25%      186.057808   186.506259   185.208006   185.988459  5.886765e+07
50%      241.038513   242.194780   239.416509   240.508962  7.763670e+07
75%      287.060120   288.240457   285.654562   286.860428  1.071577e+08
max      451.657593   453.095435   450.314435   452.083294  5.072443e+08

In [7]:
df.iloc[0]

Price   Ticker
Close   SPY       1.705896e+02
High    SPY       1.717937e+02
Low     SPY       1.695516e+02
Open    SPY       1.713785e+02
Volume  SPY       1.214659e+08
Name: 2015-01-02 00:00:00, dtype: float64

In [8]:
df.shape

(1763, 5)

In [9]:
df

Price            Close        High         Low        Open     Volume
Ticker             SPY         SPY         SPY         SPY        SPY
Date
2015-01-02  170.589645  171.793740  169.551642  171.378538  121465900
2015-01-05  167.508804  169.709366  167.201559  169.543288  169632600
2015-01-06  165.931046  168.339208  165.133853  167.816050  209151400
2015-01-07  167.998749  168.339217  166.811279  167.259691  125346700
2015-01-08  170.979950  171.195863  169.393890  169.410489  147217800
...                ...         ...         ...         ...        ...
2021-12-27  451.449493  451.496778  446.483417  446.530701   56808600
2021-12-28  451.080627  452.915714  450.314435  451.884665   47274600
2021-12-29  451.657593  452.679173  450.181961  451.184633   54503000
2021-12-30  450.409027  453.095435  449.945536  452.083294   55329000
2021-12-31  449.273865  451.071106  448.999569  449.917112   65237400

[1763 rows x 5 columns]

In [11]:
df.columns

MultiIndex([( 'Close', 'SPY'),
            (  'High', 'SPY'),
            (   'Low', 'SPY'),
            (  'Open', 'SPY'),
            ('Volume', 'SPY')],
           names=['Price', 'Ticker'])

In [23]:
prices_series = df["Close"][:120]

prices_series.rolling(20).mean().iloc[-1]

Ticker
SPY    175.995056
Name: 2015-06-24 00:00:00, dtype: float64

In [22]:
df["Close"][:10]

Ticker             SPY
Date
2015-01-02  170.589645
2015-01-05  167.508804
2015-01-06  165.931046
2015-01-07  167.998749
2015-01-08  170.979950
2015-01-09  169.609695
2015-01-12  168.281097
2015-01-13  167.807755
2015-01-14  166.794693
2015-01-15  165.266785

In [25]:
print(df["Close"])

Ticker             SPY
Date
2015-01-02  170.589645
2015-01-05  167.508804
2015-01-06  165.931046
2015-01-07  167.998749
2015-01-08  170.979950
...                ...
2021-12-27  451.449493
2021-12-28  451.080627
2021-12-29  451.657593
2021-12-30  450.409027
2021-12-31  449.273865

[1763 rows x 1 columns]